server:
  port: 21410
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
#    fetch-registry: true
#    registry-fetch-interval-seconds: 30
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000