server:
  port: 21400
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password: root
  application:
    name: user-service
mybatis:
  type-aliases-package: cn.shiki.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
logging:
  level:
    cn.shiki: debug